# Scaffolding generated by Casein v5.1.1.5

module Casein
  class FamiliesController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Families'
  		@families = Family.order(sort_order(:name)).paginate :page => params[:page]
    end

    def show
      @casein_page_title = 'View family'
      @family = Family.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new family'
    	@family = Family.new
    end

    def create
      @family = Family.new family_params

      if @family.save
        flash[:notice] = 'Family created'
        redirect_to casein_families_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new family'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update family'

      @family = Family.find params[:id]

      if @family.update_attributes family_params
        flash[:notice] = 'Family has been updated'
        redirect_to casein_families_path
      else
        flash.now[:warning] = 'There were problems when trying to update this family'
        render :action => :show
      end
    end

    def destroy
      @family = Family.find params[:id]

      @family.destroy
      flash[:notice] = 'Family has been deleted'
      redirect_to casein_families_path
    end

    private

      def family_params
        params.require(:family).permit(:name)
      end

  end
end
