# Scaffolding generated by Casein v5.1.1.5

module Casein
  class MarketsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Markets'
  		@markets = Market.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View market'
      @market = Market.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new market'
    	@market = Market.new
    end

    def create
      @market = Market.new market_params
    
      if @market.save
        flash[:notice] = 'Market created'
        redirect_to casein_markets_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new market'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update market'
      
      @market = Market.find params[:id]
    
      if @market.update_attributes market_params
        flash[:notice] = 'Market has been updated'
        redirect_to casein_markets_path
      else
        flash.now[:warning] = 'There were problems when trying to update this market'
        render :action => :show
      end
    end
 
    def destroy
      @market = Market.find params[:id]

      @market.destroy
      flash[:notice] = 'Market has been deleted'
      redirect_to casein_markets_path
    end
  
    private
      
      def market_params
        params.require(:market).permit(:name)
      end

  end
end